//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busTicketApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class guzergah
    {
        public guzergah()
        {
            this.seferBilet = new HashSet<seferBilet>();
            this.seferler = new HashSet<seferler>();
        }
    
        public int guzergah_id { get; set; }
        public int nereden { get; set; }
        public int nereye { get; set; }
        public string durak { get; set; }
    
        public virtual ICollection<seferBilet> seferBilet { get; set; }
        public virtual ICollection<seferler> seferler { get; set; }
    }
}
