//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busTicketApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiletEntities : DbContext
    {
        public BiletEntities()
            : base("name=BiletEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<guzergah> guzergah { get; set; }
        public DbSet<otobus> otobus { get; set; }
        public DbSet<seferBilet> seferBilet { get; set; }
        public DbSet<seferKoltuk> seferKoltuk { get; set; }
        public DbSet<seferler> seferler { get; set; }
        public DbSet<sehirMesafe> sehirMesafe { get; set; }
    }
}
