//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busTicketApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class otobus
    {
        public otobus()
        {
            this.seferBilet = new HashSet<seferBilet>();
            this.seferler = new HashSet<seferler>();
        }
    
        public int otobus_id { get; set; }
        public string adi { get; set; }
        public int koltukSayisi { get; set; }
        public string turu { get; set; }
        public string koltukDuzen { get; set; }
    
        public virtual ICollection<seferBilet> seferBilet { get; set; }
        public virtual ICollection<seferler> seferler { get; set; }
    }
}
