//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busTicketApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class seferKoltuk
    {
        public int seferKoltuk_id { get; set; }
        public int sefer_id { get; set; }
        public string cinsiyet { get; set; }
        public string koltukNo { get; set; }
    
        public virtual seferler seferler { get; set; }
    }
}
