//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busTicketApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class seferler
    {
        public seferler()
        {
            this.seferBilet = new HashSet<seferBilet>();
            this.seferKoltuk = new HashSet<seferKoltuk>();
        }
    
        public int sefer_id { get; set; }
        public int otobus_id { get; set; }
        public int guzergah_id { get; set; }
        public string kalkisSaati { get; set; }
        public int fiyat { get; set; }
        public System.DateTime kalkisTarihi { get; set; }
    
        public virtual guzergah guzergah { get; set; }
        public virtual otobus otobus { get; set; }
        public virtual ICollection<seferBilet> seferBilet { get; set; }
        public virtual ICollection<seferKoltuk> seferKoltuk { get; set; }
    }
}
