//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busTicketApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehirler
    {
        public double sehir_id { get; set; }
        public string sehirAdi { get; set; }
        public Nullable<double> ADANA { get; set; }
        public Nullable<double> ADIYAMAN { get; set; }
        public Nullable<double> AFYONKARAHİSAR { get; set; }
        public Nullable<double> AĞRI { get; set; }
        public Nullable<double> AMASYA { get; set; }
        public Nullable<double> ANKARA { get; set; }
        public Nullable<double> ANTALYA { get; set; }
        public Nullable<double> ARTVİN { get; set; }
        public Nullable<double> AYDIN { get; set; }
        public Nullable<double> BALIKESİR { get; set; }
        public Nullable<double> BİLECİK { get; set; }
        public Nullable<double> BİNGÖL { get; set; }
        public Nullable<double> BİTLİS { get; set; }
        public Nullable<double> BOLU { get; set; }
        public Nullable<double> BURDUR { get; set; }
        public Nullable<double> BURSA { get; set; }
        public Nullable<double> ÇANAKKALE { get; set; }
        public Nullable<double> ÇANKIRI { get; set; }
        public Nullable<double> ÇORUM { get; set; }
        public Nullable<double> DENİZLİ { get; set; }
        public Nullable<double> DİYARBAKIR { get; set; }
        public Nullable<double> EDİRNE { get; set; }
        public Nullable<double> ELAZIĞ { get; set; }
        public Nullable<double> ERZİNCAN { get; set; }
        public Nullable<double> ERZURUM { get; set; }
        public Nullable<double> ESKİŞEHİR { get; set; }
        public Nullable<double> GAZİANTEP { get; set; }
        public Nullable<double> GİRESUN { get; set; }
        public Nullable<double> GÜMÜŞHANE { get; set; }
        public Nullable<double> HAKKARİ { get; set; }
        public Nullable<double> HATAY { get; set; }
        public Nullable<double> ISPARTA { get; set; }
        public Nullable<double> MERSİN { get; set; }
        public Nullable<double> İSTANBUL { get; set; }
        public Nullable<double> İZMİR { get; set; }
        public Nullable<double> KARS { get; set; }
        public Nullable<double> KASTAMONU { get; set; }
        public Nullable<double> KAYSERİ { get; set; }
        public Nullable<double> KIRKLARELİ { get; set; }
        public Nullable<double> KIRŞEHİR { get; set; }
        public Nullable<double> KOCAELİ__İZMİT_ { get; set; }
        public Nullable<double> KONYA { get; set; }
        public Nullable<double> KÜTAHYA { get; set; }
        public Nullable<double> MALATYA { get; set; }
        public Nullable<double> MANİSA { get; set; }
        public Nullable<double> KAHRAMANMARAŞ { get; set; }
        public Nullable<double> MARDİN { get; set; }
        public Nullable<double> MUĞLA { get; set; }
        public Nullable<double> MUŞ { get; set; }
        public Nullable<double> NEVŞEHİR { get; set; }
        public Nullable<double> NİĞDE { get; set; }
        public Nullable<double> ORDU { get; set; }
        public Nullable<double> RİZE { get; set; }
        public Nullable<double> SAKARYA__ADAPAZARI_ { get; set; }
        public Nullable<double> SAMSUN { get; set; }
        public Nullable<double> SİİRT { get; set; }
        public Nullable<double> SİNOP { get; set; }
        public Nullable<double> SİVAS { get; set; }
        public Nullable<double> TEKİRDAĞ { get; set; }
        public Nullable<double> TOKAT { get; set; }
        public Nullable<double> TRABZON { get; set; }
        public Nullable<double> TUNCELİ { get; set; }
        public Nullable<double> ŞANLIURFA { get; set; }
        public Nullable<double> UŞAK { get; set; }
        public Nullable<double> VAN { get; set; }
        public Nullable<double> YOZGAT { get; set; }
        public Nullable<double> ZONGULDAK { get; set; }
        public Nullable<double> AKSARAY { get; set; }
        public Nullable<double> BAYBURT { get; set; }
        public Nullable<double> KARAMAN { get; set; }
        public Nullable<double> KIRIKKALE { get; set; }
        public Nullable<double> BATMAN { get; set; }
        public Nullable<double> ŞIRNAK { get; set; }
        public Nullable<double> BARTIN { get; set; }
        public Nullable<double> ARDAHAN { get; set; }
        public Nullable<double> IĞDIR { get; set; }
        public Nullable<double> YALOVA { get; set; }
        public Nullable<double> KARABÜK { get; set; }
        public Nullable<double> KİLİS { get; set; }
        public Nullable<double> OSMANİYE { get; set; }
        public Nullable<double> DÜZCE { get; set; }
    }
}
